version: '3.4'

services:
  domaindrivendesign.example.presentation.web.api:
    image: ${DOCKER_REGISTRY-}domaindrivendesignexamplepresentationwebapi
    build:
      context: .
      dockerfile: DomainDrivenDesign.Example.Web.Api/Dockerfile

  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=ap-southeast-1
      - EDGE_PORT=4566
      - SERVICES=dynamodb
      - KINESIS_PROVIDER=kinesalite
    ports:
      - '4566:4566'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
